esphome:
  name: esp32-cam
  friendly_name: esp32_cam

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_eencryption

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Cam Fallback Hotspot"
    password: !secret ap_password

captive_portal:

esp32_camera:
  name: "ESP32 CAM"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 640x480
  max_framerate: 10 fps
  idle_framerate: 0.1 fps

output:
  - platform: ledc
    channel: 2
    pin: GPIO4
    id: led_pwm

light:
  - platform: monochromatic
    name: "Camera Flash"
    output: led_pwm

sensor:
  - platform: wifi_signal
    name: "ESP32-CAM WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "ESP32-CAM Uptime"

switch:
  - platform: restart
    name: "ESP32-CAM Restart"

# web_server:
#   port: 80
#   include_internal: true
#   local: true
  # auth:
  #   username: wookingwoo
  #   password: !secret cam_web_pass

esp32_camera_web_server:
  - port: 81
    mode: stream
  - port: 82
    mode: snapshot
